version: "3"

services:
  frontend:
    container_name: frontend
    context: ./frontend
    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: backend
    context: ./backend
    dockerfile: Dockerfile
    ports:
      - "4000:4000"